name: CMake

on:
  push:
    branches: [ "main", "beta", "alpha" ]
  pull_request:
    branches: [ "main", "beta", "alpha" ]

env:
  BUILD_TYPE: Debug
  PICO_SDK_PATH: /usr/share/pico-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y git python3 && sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential && \
        git clone --depth 1 --branch 1.5.1 https://github.com/raspberrypi/pico-sdk ${{env.PICO_SDK_PATH}} && cd ${{env.PICO_SDK_PATH}} && git submodule update --init

    - name: Build - pico
      run: cmake -B ${{github.workspace}}/build_pico -DFBW_PLATFORM=pico -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && cmake --build_pico ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Build - pico_w
      run: cmake -B ${{github.workspace}}/build_pico_w -DFBW_PLATFORM=pico_w -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && cmake --build_pico_w ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
