name: Build

# TODO: seperate workflow for main that will build for release and auto upload artifacts
# and also run FBW_FORMAT for clang-tidy

on:
  push:
    branches: [ "main", "beta", "alpha" ]
  pull_request:
    branches: [ "main", "beta", "alpha" ]

env:
  # Debug build will enable more warnings
  BUILD_TYPE: Debug
  PICO_SDK_PATH: ${{github.workspace}}/pico-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        PLATFORM: [ pico, pico_w ]

    steps:
    - name: Checkout pico-fbw
      uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'

    - name: Set up Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.11.1

    - name: Prepare (rp2040)
      uses: Fortinbra/RaspberryPiPicoBuild@v3
      if: matrix.PLATFORM == 'pico' || matrix.PLATFORM == 'pico_w'

    - name: Prepare (espressif)
      uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.2
        target: esp32
        command: ''
      if: matrix.PLATFORM == 'esp32'

    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo | grep processor | wc -l

    - name: Configure CMake
      shell: bash
      run: cmake -B ${{github.workspace}}/build -DFBW_PLATFORM=${{matrix.PLATFORM}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja

    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}
