name: CMake

on:
  push:
    branches: [ "main", "beta", "alpha" ]
  pull_request:
    branches: [ "main", "beta", "alpha" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build - pico
      run: cmake -B ${{github.workspace}}/build -DFBW_PLATFORM=pico -DPICO_SDK_FETCH_FROM_GIT=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Build - pico_w
      run: cmake -B ${{github.workspace}}/build -DFBW_PLATFORM=pico_w -DPICO_SDK_FETCH_FROM_GIT=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
